package com.privacyguard.utils

import android.content.Context
import android.content.Intent
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Build
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

data class ReportData(
    val score: Int,
    val scoreLabel: String,
    val micApps: Int,
    val cameraApps: Int,
    val locationApps: Int,
    val suspiciousKeyloggers: Int,
    val nightEvents: Int,
    val triggerPairs: Int,
    val weekStart: Long,
    val weekEnd: Long
)

object PdfReportGenerator {

    fun generate(context: Context, data: ReportData): File {
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
        val page = doc.startPage(pageInfo)
        val canvas = page.canvas

        val fmt = SimpleDateFormat("MMM d, yyyy", Locale.getDefault())

        // ── Paints ─────────────────────────────────────────────────────────
        val titlePaint = Paint().apply { textSize = 28f; isFakeBoldText = true; color = android.graphics.Color.parseColor("#00E5FF") }
        val headerPaint = Paint().apply { textSize = 14f; isFakeBoldText = true; color = android.graphics.Color.parseColor("#FFFFFF") }
        val bodyPaint = Paint().apply { textSize = 12f; color = android.graphics.Color.parseColor("#B0BEC5") }
        val scorePaint = Paint().apply { textSize = 48f; isFakeBoldText = true }
        val linePaint = Paint().apply { color = android.graphics.Color.parseColor("#37474F"); strokeWidth = 1f }
        val bgPaint = Paint().apply { color = android.graphics.Color.parseColor("#0A1628") }

        // Background
        canvas.drawRect(0f, 0f, 595f, 842f, bgPaint)

        var y = 50f

        // Header
        canvas.drawText("🛡️  PrivacyGuard", 40f, y, titlePaint); y += 36f
        canvas.drawText("Weekly Privacy Report", 40f, y, headerPaint)

        val dateRange = "${fmt.format(Date(data.weekStart))} – ${fmt.format(Date(data.weekEnd))}"
        val dateX = 595f - bodyPaint.measureText(dateRange) - 40f
        canvas.drawText(dateRange, dateX, y, bodyPaint); y += 28f

        // Divider
        canvas.drawLine(40f, y, 555f, y, linePaint); y += 30f

        // Score section
        scorePaint.color = when {
            data.score >= 80 -> android.graphics.Color.parseColor("#69F0AE")
            data.score >= 50 -> android.graphics.Color.parseColor("#FFD740")
            else             -> android.graphics.Color.parseColor("#FF5252")
        }
        canvas.drawText("${data.score}", 40f, y + 42f, scorePaint)
        canvas.drawText("/ 100", 40f + scorePaint.measureText("${data.score}") + 6f, y + 42f, bodyPaint)
        canvas.drawText("Privacy Score  ·  ${data.scoreLabel}", 40f, y + 64f, headerPaint)
        y += 90f

        canvas.drawLine(40f, y, 555f, y, linePaint); y += 28f

        // Stats table
        canvas.drawText("THREAT BREAKDOWN", 40f, y, headerPaint); y += 22f

        fun row(label: String, value: String) {
            canvas.drawText(label, 40f, y, bodyPaint)
            canvas.drawText(value, 555f - bodyPaint.measureText(value), y, bodyPaint)
            y += 22f
        }

        row("Microphone accesses",          data.micApps.toString())
        row("Camera accesses",              data.cameraApps.toString())
        row("Location queries",             data.locationApps.toString())
        row("Suspicious accessibility apps",data.suspiciousKeyloggers.toString())
        row("Night-time background events", data.nightEvents.toString())
        row("App co-activation patterns",   data.triggerPairs.toString())

        y += 20f
        canvas.drawLine(40f, y, 555f, y, linePaint); y += 28f

        // Recommendation
        canvas.drawText("RECOMMENDATIONS", 40f, y, headerPaint); y += 22f

        if (data.suspiciousKeyloggers > 0)
            canvas.drawText("• Revoke Accessibility permissions from unknown apps.", 40f, y, bodyPaint).also { y += 22f }
        if (data.nightEvents > 5)
            canvas.drawText("• Enable battery optimization for apps active at night.", 40f, y, bodyPaint).also { y += 22f }
        if (data.cameraApps > 3)
            canvas.drawText("• Review camera permissions for non-camera apps.", 40f, y, bodyPaint).also { y += 22f }
        if (data.locationApps > 5)
            canvas.drawText("• Use precise location only when needed.", 40f, y, bodyPaint).also { y += 22f }
        if (data.score >= 80)
            canvas.drawText("• Great job! Keep reviewing permissions regularly.", 40f, y, bodyPaint).also { y += 22f }

        y += 30f
        canvas.drawLine(40f, y, 555f, y, linePaint); y += 20f
        bodyPaint.textSize = 10f
        canvas.drawText("Generated by PrivacyGuard · ${fmt.format(Date())} · All data stored locally on device.", 40f, y, bodyPaint)

        doc.finishPage(page)

        val dir = File(context.getExternalFilesDir(null), "reports").also { it.mkdirs() }
        val file = File(dir, "PrivacyGuard_Report_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()

        return file
    }

    fun share(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Privacy Report").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        })
    }
}
